const groups=[
{id:"netflix",name:"Netflix Premium",cat:"Streaming",img:"assets/products/netflix.svg",badge:"HOT",packs:[
["1 BULAN SHARING (1U)",42000],["1 BULAN SHARING (2U)",24000],["1 BULAN SEMI PRIVATE",47000]]},
{id:"viu",name:"Viu Premium",cat:"Streaming",img:"assets/products/viu.svg",badge:"NEW",packs:[
["1 BULAN PREMIUM",10000],["1 TAHUN PREMIUM",65000]]},
{id:"youtube",name:"YouTube Premium",cat:"Streaming",img:"assets/products/youtube.svg",badge:"HOT",packs:[
["1 BULAN INDIVIDUAL",15000],["3 BULAN INDIVIDUAL",35000]]},
{id:"prime",name:"Prime Video",cat:"Streaming",img:"assets/products/prime.svg",packs:[
["1 BULAN SHARING",10000],["1 BULAN PRIVATE",30000]]},
{id:"iqiyi",name:"iQIYI Premium",cat:"Streaming",img:"assets/products/iqiyi.svg",badge:"HOT",packs:[
["1 BULAN SHARING (STANDARD)",7000],["1 TAHUN SHARING (STANDARD)",17000],["1 BULAN SHARING (PREMIUM)",10000],["1 TAHUN SHARING (PREMIUM)",20000],["1 BULAN PRIVATE (STANDARD)",35000],["1 BULAN PRIVATE (PREMIUM)",40000]]},
{id:"canva",name:"Canva Pro",cat:"Design",img:"assets/products/canva.svg",badge:"NEW",packs:[["1 BULAN",10000]]},
{id:"capcut",name:"CapCut Pro",cat:"Editing",img:"assets/products/capcut.svg",badge:"HOT",packs:[["1 BULAN",15000]]},
{id:"chatgpt",name:"ChatGPT Plus",cat:"AI Tools",img:"assets/products/ai.svg",packs:[["1 BULAN",25000]]},
{id:"office",name:"Microsoft 365",cat:"Productivity",img:"assets/products/office.svg",packs:[["1 BULAN",15000]]}
];

let cart=JSON.parse(localStorage.getItem("vdm_cart")||"[]");
let orders=JSON.parse(localStorage.getItem("vdm_orders")||"[]");
let user=JSON.parse(localStorage.getItem("vdm_user")||"null");
let theme=localStorage.getItem("vdm_theme")||"dark";
let accent=localStorage.getItem("vdm_accent")||"#d6a634";
const $=s=>document.querySelector(s);
const money=n=>"Rp "+new Intl.NumberFormat("id-ID").format(n);
function applyTheme(){document.documentElement.style.setProperty("--accent",accent);document.documentElement.style.setProperty("--primary",accent);document.body.dataset.theme=theme;document.documentElement.style.setProperty("--bg",theme==="light"?"#f5f6fa":"#08090d");document.documentElement.style.setProperty("--surface",theme==="light"?"#fff":"#101219");document.documentElement.style.setProperty("--surface2",theme==="light"?"#fff":"#151822");document.documentElement.style.setProperty("--text",theme==="light"?"#151722":"#f7f7fa");}
applyTheme();
function save(){localStorage.setItem("vdm_cart",JSON.stringify(cart));localStorage.setItem("vdm_orders",JSON.stringify(orders));}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2000)}
function totalCart(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
function card(g){return `<article class="card"><div class="poster">${g.badge?`<span class="tag hot">${g.badge==="HOT"?"🔥 ":""}${g.badge}</span>`:""}<img src="${g.img}" alt="${g.name}"></div><div class="body"><div class="title">${g.name}</div><div class="packline">${g.packs.length} pilihan paket tersedia</div><div class="price">mulai ${money(Math.min(...g.packs.map(x=>x[1])))}</div><button class="choose" onclick="detail('${g.id}')">Pilih Paket</button></div></article>`}
function header(){return `<header class="top"><nav class="nav"><button class="circle" onclick="openSide()">☰</button><button class="logo" onclick="home()"><img src="assets/vdm-logo.svg"><span><b>VDM | VEX DIGITAL MARKET</b><small>YOUR PREMIUM DIGITAL STORE</small></span></button><div class="navlinks"><button onclick="home()">Home</button><button onclick="catalog()">Katalog</button><button onclick="ordersPage()">Pesanan</button></div><button class="circle" onclick="search()">⌕</button><button class="circle" onclick="openCart()">🛍️<span class="count">${cart.reduce((a,x)=>a+x.qty,0)}</span></button><button class="circle" onclick="preference()">◐</button></nav></header>`}
function home(){
 document.title="VDM | VEX DIGITAL MARKET";
 const hot=groups.filter(g=>g.badge==="HOT"), fresh=groups.filter(g=>g.badge==="NEW");
 $("#app").innerHTML=header()+`<main class="wrap"><section class="hero"><div class="hero-box"><div class="eyebrow">VDM | VEX DIGITAL MARKET</div><h1>Premium digital products, with a VEX atmosphere.</h1><p>Belanja produk digital pilihan dengan checkout sederhana, sistem member, dan bantuan customer support.</p><div class="actions"><button class="btn" onclick="catalog()">Mulai Belanja</button><button class="btn ghost" onclick="ordersPage()">Pesanan Saya</button></div></div></section>
<section class="section"><div class="head"><div><h2>🔥 Flash Sale</h2><p>Produk pilihan dengan paket yang sedang diminati.</p></div><button class="btn ghost" onclick="catalog()">Lihat semua</button></div><div class="rail auto" id="hot">${hot.map(card).join("")}</div></section>
<section class="section"><div class="head"><div><h2>⭐ Produk Terpopuler</h2><p>Produk favorit customer VEX.</p></div></div><div class="grid">${groups.slice(0,8).map(card).join("")}</div></section>
<section class="section"><div class="head"><div><h2>✨ Produk Baru</h2><p>Koleksi terbaru.</p></div></div><div class="rail auto" id="fresh">${fresh.map(card).join("")}</div></section></main>${footer()}`;
}
function footer(){return `<footer class="footer">© 2026 VDM | VEX DIGITAL MARKET · Premium digital store</footer>`}
function catalog(cat="Semua"){
 const cats=["Semua","Streaming","Design","AI Tools","Editing","Productivity"];
 const list=cat==="Semua"?groups:groups.filter(g=>g.cat===cat);
 $("#app").innerHTML=header()+`<main class="wrap"><div class="back"><button onclick="home()">⤶ Kembali</button></div><div class="head"><div><h2>Katalog</h2><p>Setiap produk memiliki pilihan paket di dalamnya.</p></div></div><div class="chips">${cats.map(c=>`<button class="chip ${c===cat?"active":""}" onclick="catalog('${c}')">${c}</button>`).join("")}</div><div class="grid">${list.map(card).join("")}</div></main>${footer()}`;
}
function detail(id){
 const g=groups.find(x=>x.id===id);let idx=0;
 const show=()=>{const p=g.packs[idx];$("#modal").innerHTML=`<div class="modal"><div class="modal-head"><h3>${g.name}</h3><button class="close" onclick="closeModal()">✕</button></div><div class="product-detail"><img class="detail-img" src="${g.img}"><div><div class="muted">${g.cat}</div><h2 style="margin:5px 0">${g.name}</h2><p class="muted">Pilih paket yang kamu inginkan. Satu produk tetap satu kartu; paket dikelola di dalam detail produk.</p><div class="options">${g.packs.map((x,i)=>`<button class="option ${i===idx?"active":""}" onclick="selectPack(${i})">${x[0]}</button>`).join("")}</div><div class="price" style="font-size:24px">${money(p[1])}</div><button class="btn" style="width:100%;margin-top:15px" onclick="addCart('${g.id}',${idx})">🛒 Beli Sekarang</button></div></div></div>`;};
 window.selectPack=i=>{idx=i;show()};openModal();show();
}
function openModal(){let x=$("#modal");if(!x){document.body.insertAdjacentHTML("beforeend",`<div class="modal-wrap" id="modal"></div>`);x=$("#modal")}x.classList.add("open")}
function closeModal(){$("#modal")?.remove()}
function addCart(id,idx){const g=groups.find(x=>x.id===id),pack=g.packs[idx],key=id+"-"+idx;const found=cart.find(x=>x.key===key);if(found)found.qty++;else cart.push({key,id,idx,name:g.name,pack:pack[0],price:pack[1],img:g.img,qty:1});save();closeModal();toast("Produk masuk keranjang 🛍️");home()}
function openCart(){openModal();const body=cart.length?cart.map(x=>`<div class="cart-row"><div class="thumb"><img src="${x.img}"></div><div><b>${x.name}</b><div class="muted">${x.pack} · ${money(x.price)} × ${x.qty}</div></div><button class="close" onclick="removeItem('${x.key}')">×</button></div>`).join("")+`<div class="total"><span>Total</span><span>${money(totalCart())}</span></div><button class="btn" style="width:100%" onclick="checkout()">Lanjut Checkout</button>`:`<div class="empty">Keranjang masih kosong.</div>`;$("#modal").innerHTML=`<div class="modal"><div class="modal-head"><h3>Keranjang</h3><button class="close" onclick="closeModal()">✕</button></div>${body}</div>`}
function removeItem(k){cart=cart.filter(x=>x.key!==k);save();openCart()}
function checkout(){if(!cart.length)return toast("Keranjang masih kosong.");if(!user){closeModal();login(true);return}closeModal();openModal();$("#modal").innerHTML=`<div class="modal"><div class="modal-head"><h3>Checkout</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form"><div class="field"><label>Email pengiriman produk</label><input id="delivery" type="email" placeholder="email tujuan delivery"></div><div class="field"><label>Metode pembayaran</label><select id="payment"><option>QRIS</option><option>Virtual Account</option><option>E-Wallet</option></select></div><div class="field"><label>Catatan</label><textarea id="note" rows="3" placeholder="Opsional"></textarea></div><div class="total"><span>Total</span><span>${money(totalCart())}</span></div><button class="btn" onclick="createOrder()">Buat Pesanan</button></div></div>`}
function createOrder(){const email=$("#delivery").value.trim();if(!email.includes("@"))return toast("Email pengiriman belum valid.");orders.unshift({id:"VDM-"+Date.now().toString().slice(-7),createdAt:new Date().toISOString(),account:user.email,deliveryEmail:email,items:[...cart],total:totalCart(),status:"PENDING"});cart=[];save();closeModal();toast("Pesanan berhasil dibuat");ordersPage()}
function login(after=false){openModal();$("#modal").innerHTML=`<div class="glass"><div class="glass-inner"><div class="modal-head"><h3>Login / Daftar VDM</h3><button class="close" onclick="closeModal()">✕</button></div><p class="muted">Kamu tetap bisa browsing sebagai Guest. Login hanya diperlukan ketika checkout.</p><div class="form"><div class="field"><label>Nama</label><input id="lname" placeholder="Nama kamu"></div><div class="field"><label>Gmail</label><input id="lemail" type="email" placeholder="nama@gmail.com"></div><div class="field"><label>Password akun</label><input id="lpass" type="password" placeholder="Minimal 6 karakter"></div><button class="btn" onclick="loginNow(${after})">Masuk</button><button class="btn ghost" onclick="googleLogin(${after})">G Continue with Google</button></div></div></div>`}
function loginNow(after){const name=$("#lname").value.trim()||"VDM Member",email=$("#lemail").value.trim(),pass=$("#lpass").value;if(!email.includes("@"))return toast("Gmail belum valid.");if(pass.length<6)return toast("Password minimal 6 karakter.");user={name,username:email.split("@")[0],email,createdAt:new Date().toISOString()};localStorage.setItem("vdm_user",JSON.stringify(user));closeModal();toast("Login berhasil 👋");if(after)checkout();else preference()}
function googleLogin(after){toast("Google OAuth akan diaktifkan pada backend production.");}
function ordersPage(){if(!user)return login(false);$("#app").innerHTML=header()+`<main class="wrap"><div class="back"><button onclick="home()">⤶ Kembali</button></div><h2>Pesanan Saya</h2><p class="muted">Riwayat pesanan akun ${user.email}.</p>${orders.filter(o=>o.account===user.email).map(o=>`<div class="order"><div><b>${o.id}</b><div class="muted">${new Date(o.createdAt).toLocaleString("id-ID")} · Delivery: ${o.deliveryEmail}</div></div><div style="text-align:right"><span class="status">${o.status}</span><div class="price">${money(o.total)}</div></div></div>`).join("")||`<div class="order">Belum ada pesanan.</div>`}</main>${footer()}`}
function preference(){openModal();$("#modal").innerHTML=`<div class="modal"><div class="modal-head"><h3>Preference</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form"><div><b>Appearance</b><p class="muted">Mode Dark / Light berada di Preference.</p><div class="preference"><button class="theme-btn ${theme==="dark"?"active":""}" onclick="setTheme('dark')">🌙 Dark</button><button class="theme-btn ${theme==="light"?"active":""}" onclick="setTheme('light')">☀️ Light</button></div></div><div><b>Accent Theme</b><p class="muted">Semua glow, petir, streak, tombol, badge dan hover mengikuti warna ini.</p><div class="preference"><button class="theme-btn" onclick="setAccent('#d6a634')">Gold</button><button class="theme-btn" onclick="setAccent('#38bdf8')">Blue</button><button class="theme-btn" onclick="setAccent('#a855f7')">Purple</button></div></div></div></div>`}
function setTheme(t){theme=t;localStorage.setItem("vdm_theme",t);applyTheme();preference();toast("Theme diperbarui")}
function setAccent(c){accent=c;localStorage.setItem("vdm_accent",c);applyTheme();preference();toast("Accent diperbarui")}
function profile(){openModal();const since=user?new Date(user.createdAt).toLocaleDateString("id-ID",{month:"short",year:"numeric"}):"—";$("#modal").innerHTML=`<div class="modal"><div class="modal-head"><h3>Pengaturan</h3><button class="close" onclick="closeModal()">✕</button></div><div class="account"><div class="avatar">${user?user.name[0].toUpperCase():"?"}</div><div><b>${user?user.name:"Guest"}</b><div class="muted">${user?user.email:"Belum login"}</div><div class="member">★ VIP Member · MEMBER</div></div></div>${user?`<div class="form"><div class="field"><label>Nama</label><input id="pname" value="${user.name}"></div><div class="field"><label>Username</label><input id="puser" value="${user.username}"></div><div class="field"><label>Gmail akun</label><input value="${user.email}" disabled></div><div class="muted">Member sejak ${since}</div><button class="btn" onclick="saveProfile()">Simpan Profil</button><button class="btn ghost" onclick="logout()">Logout</button></div>`:`<button class="btn" style="width:100%" onclick="closeModal();login()">Login / Daftar</button>`}`}
function saveProfile(){user.name=$("#pname").value.trim()||user.name;user.username=$("#puser").value.trim()||user.username;localStorage.setItem("vdm_user",JSON.stringify(user));toast("Profil disimpan");profile()}
function logout(){user=null;localStorage.removeItem("vdm_user");closeModal();toast("Logout berhasil");home()}
function help(){openModal();$("#modal").innerHTML=`<div class="modal"><div class="modal-head"><h3>Pusat Bantuan</h3><button class="close" onclick="closeModal()">✕</button></div><p class="muted">VEX Assistant 24 jam akan menangani pertanyaan customer berdasarkan data resmi toko.</p><div class="menu"><button onclick="toast('Siapkan Order ID untuk bantuan pesanan.')">🧾 Masalah Pesanan</button><button onclick="toast('Email delivery boleh berbeda dari Gmail akun.')">📧 Email Delivery</button><button onclick="toast('Payment production akan terhubung ke gateway.')">💳 Pembayaran</button><button onclick="toast('AI tidak boleh mengarang data toko.')">🤖 VEX Assistant</button></div></div>`}
function openSide(){document.body.insertAdjacentHTML("beforeend",`<div class="overlay open" id="side"><div class="drawer"><div class="drawer-head"><h3>VDM | VEX</h3><button class="close" onclick="closeSide()">✕</button></div><div class="account"><div class="avatar">${user?user.name[0].toUpperCase():"?"}</div><div><b>${user?user.name:"Guest"}</b><div class="muted">${user?user.email:"Belum login"}</div><div class="member">${user?"★ VIP Member · MEMBER":"GUEST"}</div></div></div><div class="menu"><button onclick="closeSide();home()">🏠 Dashboard</button><button onclick="closeSide();ordersPage()">🧾 Pesanan Saya</button><button onclick="closeSide();help()">❓ Pusat Bantuan</button><button onclick="closeSide();profile()">⚙️ Pengaturan</button><button class="store" onclick="closeSide();home()">↩ Balik ke Toko</button></div></div></div>`)}
function closeSide(){$("#side")?.remove()}
function search(){openModal();$("#modal").innerHTML=`<div class="modal"><div class="modal-head"><h3>Cari Produk</h3><button class="close" onclick="closeModal()">✕</button></div><div class="field"><input id="q" autofocus placeholder="Cari produk..." oninput="doSearch()"></div><div id="results" class="grid" style="grid-template-columns:repeat(2,1fr);margin-top:14px"></div></div>`;doSearch()}
function doSearch(){const q=($("#q")?.value||"").toLowerCase();$("#results").innerHTML=groups.filter(g=>(g.name+" "+g.cat).toLowerCase().includes(q)).map(card).join("")||"<div class='muted'>Produk tidak ditemukan.</div>"}
function auto(){document.querySelectorAll(".auto").forEach(r=>{if(r.scrollWidth>r.clientWidth)r.scrollBy({left:240,behavior:"smooth"})})}
setInterval(auto,4200);
window.home=home;window.catalog=catalog;window.ordersPage=ordersPage;window.detail=detail;window.openCart=openCart;window.checkout=checkout;window.openSide=openSide;window.closeSide=closeSide;window.preference=preference;window.profile=profile;window.help=help;window.search=search;window.closeModal=closeModal;window.addCart=addCart;window.removeItem=removeItem;window.login=login;window.googleLogin=googleLogin;window.setTheme=setTheme;window.setAccent=setAccent;window.saveProfile=saveProfile;window.logout=logout;
home();
